kind: pipeline
name: default

trigger:
  branch:
    - master
    - alpha
    - beta
    - rc
  event:
    - push

steps:
  - name: lint
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile
      - yarn lint

  - name: test
    image: node:current-alpine
    commands:
      - yarn test

  - name: build
    image: node:current-alpine
    commands:
      - yarn build

  - name: semantic-release
    image: cenk1cenk2/semantic-release-drone
    settings:
      mode: release
      git_method: gh
      update_readme: true
      git_user_name:
        from_secret: GITHUB_USERNAME
      git_user_email:
        from_secret: GITHUB_EMAIL
      github_token:
        from_secret: GITHUB_TOKEN
      npm_token:
        from_secret: NPM_TOKEN
    when:
      branch:
        - master
        - alpha
        - beta
        - rc
      event:
        - push
