kind: pipeline
name: default

trigger:
  event:
    - tag
  branch:
    - master

steps:
  - name: test
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile
      - yarn lint
      - ls
      - pwd
      - exit
    volumes:
      - name: cache
        path: /cache

  - name: transpile
    image: node:current-alpine
    commands:
      - mv -f /cache/.* /cache/* ./
      - yarn build
      - mv -f ./.* ./* /cache
    volumes:
      - name: cache
        path: /cache

  - name: publish
    image: node:current-alpine
    commands:
      - mv -f /cache/.* /cache/* ./
      - yarn global add npm-cli-login
      - npm-cli-login -u $NPM_USERNAME -p $NPM_PASSWORD
      - npm publish --access public
      - npm logout
    environment:
      NPM_USERNAME:
        from_secret: NPM_USERNAME
      NPM_PASSWORD:
        from_secret: NPM_PASSWORD
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    temp: {}
